# Generated by Django 4.2.1 on 2023-07-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='produc',
            new_name='product',
        ),
    ]
