# Generated by Django 4.2.1 on 2023-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_image', models.ImageField(default='No image available', upload_to='photos/author')),
                ('author_discription', models.TextField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
    ]
