# Generated by Django 4.2.3 on 2023-07-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Return', 'Return'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150),
        ),
    ]
