# Generated by Django 4.2.3 on 2023-07-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Return', 'Return'), ('Shipped', 'Shipped'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
