# Generated by Django 4.2.3 on 2023-07-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Return', 'Return'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Processing', 'Processing')], default='Pending', max_length=150),
        ),
    ]
