# Generated by Django 4.2.3 on 2023-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0027_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Return', 'Return'), ('Delivered', 'Delivered')], default='Pending', max_length=150),
        ),
    ]
