# Generated by Django 4.2.1 on 2023-06-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('authors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(choices=[('100 TO 200', '100 TO 200'), ('200 TO 300', '200 TO 300'), ('300 TO 400', '300 TO 400'), ('400 TO 500', '400 TO 500'), ('500 and above', '500 and above')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(default='No image available', upload_to='photos/product')),
                ('product_description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pricefilter')),
            ],
        ),
    ]
