# Generated by Django 4.2.1 on 2023-07-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description_detailed',
            field=models.TextField(blank=True),
        ),
    ]
